name: build

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10.2"

      - name: Build plugin
        run: gradle build --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: halo-plugin-fmimage
          path: build/libs/*.jar
